apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication
spec:
  selector:
    matchLabels:
      app: myapplication
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapplication
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080

